### ISSUE TITLE
GORM field tags are not being processed

### ISSUE THREAD

**Issue by gdsoumya** [dipdup-io/metadata#17]
The primary key and index specifications made using gorm tag in the structs are not being processed when the tables are generated in postgres.

Reference :
 https://github.com/dipdup-net/metadata/blob/a4d18d7b27f576d6460a0c6d47aae1a2e8b555f9/cmd/metadata/models/token_metadata.go#L11-L27
![pk](https://user-images.githubusercontent.com/44349253/149663679-def7c9ab-7f90-4ab7-b364-b13e997fa9c6.png)

According to the token_metadata struct there should be a composite pk on token_id, contract and network but when I described the table it shows id as the only pk. I am using PostgresSQL v14.1

**Comment by aopoltorzhicky** [comment]
Hi! Gorm is not used in indexer. We used it earlier, but now we use pg-go. Gorm tags will be remove later.
