### ISSUE TITLE
How to set up

### ISSUE THREAD

**Issue by 852Kerfunkle** [dipdup-io/metadata#19]
Heya, this is looking amazing. Currently I'm indexing metadata in dipdup-py. It's a little tedious that way.

I suppose I drop my dipdup-py config into the build dir and build run the container build? Or is there some way to reference an external config that I missed?

Thanks.

**Comment by m-kus** [comment]
Hey! What's your ultimate goal? Do you want to use metadata API in your dipdup indexer or just as a standalone service?

**Comment by 852Kerfunkle** [comment]
I'd like to use this as a plugin in dipdup-py.

**Comment by m-kus** [comment]
Ok, in your dipdup.yml:

```
datasources:
  metadata_mainnet:
    kind: metadata
    network: mainnet
```

In your handler/job file:

```
from dipdup.datasources.metadata.datasource import MetadataDatasource

...
metadata = cast(MetadataDatasource, ctx.datasources["metadata_mainnet"])
...
res = await metadata.get_token_metadata(token_address, token_id)
res = await metadata.get_contract_metadata(contract_address)
```

It will soon be possible to do
```
metadata = ctx.get_metadata_datasource("metadata_mainnet")
```
https://github.com/dipdup-net/dipdup-py/pull/223

And also send arbitrary GQL queries (now you are limited with methods exposed in https://github.com/dipdup-net/dipdup-py/blob/master/src/dipdup/datasources/metadata/datasource.py)

Please let me know if that's enough for your use case or not, also we can continue the discussion in https://discord.gg/AuHcrmM8 if you'd like :) I think it would also be helpful for other community members

**Comment by 852Kerfunkle** [comment]
Ah, ok get it now...

And for my local dev setup, or if I want to run my own metadata indexer in prod, I would build the docker image with a modified config linking to my rpc node etc?

Yes, I've seen these pull requests, waiting anxiously for 4.2.0 :)

Thanks! I'll join the discord.

**Comment by m-kus** [comment]
Yes! The configuration file format is slightly different from the one used in dipdup though:
https://docs.dipdup.net/plugins/metadata
