### ISSUE TITLE
TokenInfo.token_id is fixed point decimal

### ISSUE THREAD

**Issue by 852Kerfunkle** [dipdup-io/metadata#24]
Seems a bit odd to me, but maybe there's a specific reason?

Maybe uint64 makes more sense here. Decimal turns out to be `numeric` instead of `bigint` in the gql schema, which makes for some odd queries.

**Comment by m-kus** [comment]
`token_id` is of type `nat` in Michelson with is unbound natural number.
Technically we should better use string type, but numeric with large enough precision is ok too

**Comment by 852Kerfunkle** [comment]
Yeah, I assumed that's the reasoning, but is there a case where something would reasonably exceed uint64? I guess the point is that that may happen.

I haven't looked into the specifics, but there is big.Int. Does that translate to postgresql and graphql better maybe?

**Comment by m-kus** [comment]
Yes there are plenty of cases, most of them don't make any sense but we have to handle them anyways.

**Comment by 852Kerfunkle** [comment]
Yeah, makes sense. Also checked the postgres docs by now and found the only way to get arbitrary length ints is by way of numeric.

Thanks!
